
var txtIntro = {
	id: 'bj_01',
    title: 'Business Justification: Introduction',
    comment: [
        'The purpose of this chapter is to understand the concept and purpose of Business Justification as it relates to Scrum projects. It is important for an organization to perform a proper business justification and create a viable Project Vision Statement prior to starting any project. This helps key decision makers understand the business need for a change or for a new product or service and the justification for moving forward with a project. It also helps the Product Owner to create a Prioritized Product Backlog along with the business expectations of Senior Management & Stakeholder(s).',
        'Business Justification, as defined in A Guide to the Scrum Body of Knowledge (SBOK™ Guide), is applicable to the following:',
        '•	Portfolios, programs, and/or projects in any industry',
        '•	Products, services, or any other results to be delivered to stakeholders',
        '•	Projects of any size or complexity',
        'The term “product” in the SBOK™ Guide may refer to a product, service, or other deliverables. Scrum can be applied effectively to any project in any industry—from small projects or teams with as few as six team members to large, complex projects with up to several hundred team members.'
    ]
};

var txtRole = {
	id: 'bj_02',
    title: 'Business Justification: Roles guide',
    comment: [
        '<b>Product Owner</b>—Business justification is primarily conducted by the Product Owner; therefore, this entire chapter is most applicable to this role.',
        '<b>Scrum Master</b>—The Scrum Master should be familiar with this entire chapter, with primary focus on sections 4.3, 4.4, 4.6, 4.7 and 4.8.',
        '<b>Scrum Team</b>—The Scrum Team should focus primarily on sections 4.3, 4.7 and 4.8.'
    ]
};

var bj_VDD = {
	id: 'bj_03',
    title: 'Value-driven Delivery',
	stitle: 'vdd',
    comment: [
    'A project is a collaborative enterprise to either create new products or services or to deliver results as defined in the Project Vision Statement. Projects are usually impacted by constraints of time, cost, scope, quality, people, and organizational capabilities. Usually, the results generated by projects are expected to create some form of business or service value.',
    'Since value is a primary reason for any organization to move forward with a project, Value-driven Delivery must be the main focus. Delivering value is ingrained in the Scrum framework. Scrum facilitates delivery of value very early on in the project and continues to do so throughout the project lifecycle.',
    'One of the key characteristics of any project is the uncertainty of results or outcomes. It is impossible to guarantee project success at completion, irrespective of the size or complexity of a project. Considering this uncertainty of achieving success, it is therefore important to start delivering results as early in the project as possible. This early delivery of results, and thereby value, provides an opportunity for reinvestment and proves the worth of the project to interested stakeholders.',
    'In order to provide Value-driven Delivery, it is important to:',
    '•	Understand what adds value to customers and users and to prioritize the high value requirements on the top of the Prioritized Product Backlog.',
    '•	Decrease uncertainty and constantly address risks that can potentially decrease value if they materialize. Also work closely with project stakeholders showing them product increments at the end of each Sprint, enabling effective management of changes.',
    '•	Create Deliverables based on the priorities determined by producing potentially shippable product increments during each Sprint so that customers start realizing value early on in the project.',
    'The concept of Value-driven Delivery in Scrum makes Scrum framework very attractive for business stakeholders and senior management. This concept is very different when compared with traditional project management models where:',
    '1.	Requirements are not prioritized by business value.',
    '2.	Changing requirements after project initiation is difficult and can only be done through a time consuming change management process.',
    '3.	Value is realized only at the end of the project when the final product or service is delivered.'
    ],
    image: '../images/bj_value.png'
};

var bj_responwer = {
	id: 'bj_04',
    title: 'Responsibilities of the Product Owner',
	stitle: 'rpo',
    comment: [
        'The responsibility of prioritizing and delivering business value in an organization for projects lies primarily with the Product Owner. For programs and portfolios, the responsibility lies with the Program Product Owner and Portfolio Product Owner, respectively. Their role is to act as effective representatives of the customer and/or sponsor. The guidelines for evaluating and measuring business value may typically be set forth by a Scrum Guidance Body.'
    ],
    image: '../images/bj_hierarchy.png'
};

var bj_respother = {
	id: 'bj_05',
	title: 'Responsibilities of Other Scrum Roles',
	stitle: 'others',
	comment: [
            'It is important to note that although the Product Owner is primarily responsible for business justification, other persons working in Scrum projects also contribute significantly as follows:',
            '1.	The <b>sponsor</b> provides funding for the project and constantly monitors the project to confirm realization of benefits.',
            '2.	<b>Customers</b> and <b>users</b> are involved in defining the prioritized list of requirements and User Stories in the Prioritized Product Backlog, reviewing Deliverables after every Sprint or release, and confirming that benefits are realized.',
            '3.	The <b>Scrum Guidance Body</b> may provide guidelines and recommendations related to business justification techniques and confirming benefits realization and so forth. Such guidelines and recommendations may then be referred to by Scrum Core Teams and Stakeholder(s).',
            '4.	The <b>Scrum Master</b> facilitates creation of the project’s deliverables; manages risks, changes, and impediments during Conduct Daily Standup, Retrospect Sprint, and other Scrum processes. The Scrum Master coordinates with the Scrum Team to create the deliverables and with the Product Owner and other stakeholders to ensure that benefits from the project are realized.',
            '5.	The <b>Scrum Team</b> works on creating the deliverables of the project and contributes to realizing business value for all stakeholders and the project. The Scrum Team is also involved in the Develop Epic(s); Create Prioritized Product Backlog; Create User Stories; Approve, Estimate, and Commit User Stories; and associated processes where the business requirements are defined and prioritized. The Scrum Team also helps in identifying risks and submits Change Requests for improvements in Sprint Retrospect Meetings and other meetings.'
    ]
};

var txtVdd = {
    id: 'bj_06',
    title: 'Business Justification',
    overview: bj_VDD,
    resp_owner: bj_responwer,
    resp_other: bj_respother 
};

var bj_factors = {
    id: 'bj_07',
    title: 'Factors Used to Determine Business Justification',
    stitle: 'factors',
    comment: [
        'There are numerous factors a Product Owner must consider to determine the business justification for a project. The following are some of the most important factors:',
        '1.	<b>Project Reasoning</b> : Project reasoning includes all factors which necessitate the project, whether positive or negative, chosen or not (e.g., inadequate capacity to meet existing and forecasted demand, decrease in customer satisfaction, low profit, legal requirement, etc.).',
        '2.	<b>Business Needs</b>: Business needs are those business outcomes that the project is expected to fulfill, as documented in the Project Vision Statement.',
        '3.	<b>Project Benefits</b>: Project benefits include all measurable improvements in a product, service, or result which could be provided through successful completion of a project.',
        '4.	<b>Opportunity Cost</b>: Opportunity cost covers the next best business option or project that was discarded in favor of the current project.',
        '5.	<b>Major Risks</b>: Risks include any uncertain or unplanned events that may affect the viability and potential success of the project.',
        '6.	<b>Project Timescales</b>: Timescales reflect the length or duration of a project and the time over which its benefits will be realized.',
        '7.	<b>Project Costs</b>: Project costs are investment and other development costs for a project.'
    ]
};

var bj_lifecycle = {
    id: 'bj_08',
    title: 'Business Justification and the Project Lifecycle',
    stitle: 'lifecycle',
    comment: [
            'Business justification is first assessed prior to a project being initiated and is continuously verified throughout the project lifecycle. The following steps capture how business justification is determined:',
            '1.	<b>Assess and Present a Business Case</b>: Business justification for a project is typically analyzed and confirmed by the Product Owner. It is documented and presented in the form of a project Business Case prior to Initiate phase and involves considering the various factors specified in section 4.4.1. Once documented, the Product Owner should create a Project Vision Statement and obtain approval of the Project Vision Statement from the key decision-makers in the organization. Generally, this consists of executives and/or some form of a project or program management board.',
            '2.	<b>Continuous Value Justification</b>: Once the decision makers approve the Project Vision Statement, it is then baselined and forms the business justification. The business justification is validated throughout project execution, typically at predefined intervals or milestones, such as during portfolio, program, and Prioritized Product Backlog Review Meetings and when major issues and risks that threaten project viability are identified. This could happen in several Scrum processes including Conduct Daily Standup and Groom Prioritized Product Backlog. Throughout the project, the Product Owner should keep the business justification in the Project Vision Statement updated with relevant project information to enable the key decision makers to continue making informed decisions.',
            '3.	<b>Confirm Benefits Realization</b>: The Product Owner confirms the achievement of organizational benefits throughout the project, as well as upon completion of the User Stories in the Prioritized Product Backlog. Benefits from Scrum projects are realized during Demonstrate and Validate Sprint, Retrospect Sprint, Ship Deliverables and Retrospect Project processes.'
    ],
    image: '../images/bj_lifecycle.png'
};

var bj_31 = {
	id: 'bj_31',
    title: 'Importance of Business Justification',
    comment: [
            'Business justification demonstrates the reasons for undertaking a project. It answers the question “Why is this project needed?” Business justification drives all decision making related to a project. So, it is important to assess the viability and achievability of a project not only before committing to significant expenditures or investment at initial stages of the project but also to verify the business justification for continuance throughout the project’s lifecycle. A project should be terminated if it is found to be unviable; the decision should be escalated to the relevant stakeholders and to senior management. The business justification for a project must be assessed at the beginning of the project, at pre-defined intervals throughout the project, and at any time when major issues or risks that threaten the project viability arise.'
        ] 
}

var txtImportance = {
    id: 'bj_09',
    overview: bj_31,
    factors: bj_factors,
    lifecycle: bj_lifecycle
};

var bj_roi = {
    id: 'bj_10',
    title: '1.	Return on Investment (ROI)',
    comment: [
        'Return on Investment (ROI) when used for project justification, assesses the expected net income to be gained from a project. It is calculated by deducting the expected costs or investment of a project from its expected revenue and then dividing this (net profit) by the expected costs in order to get a return rate. Other factors such as inflation and interest rates on borrowed money may be factored into ROI calculations.',
        'ROI formula: ',
        '<center>ROI = (Project Revenue - Project Cost) / Project Cost</center>',
        'Frequent product or service increments, is a key foundation of Scrum that allows earlier verification of ROI. This aids in assessing the justification of continuous value.'
     ]
};

var bj_roiExample = {
    id: 'bj_11',
    title: 'Example',
    comment: [
        'The ROI for a project that will cost $125,000 to develop, with expected financial benefits estimated at $300,000 is calculated as follows:',
        'ROI = ($300,000 - $125,000) / $125,000 = 1.4',
        'Therefore, the ROI is 1.4 times the investment (or 140%).'
    ]
};

var bj_npv = {
    id: 'bj_12',
    title: '2.	Net Present Value (NPV)',
    comment: [
        'Net Present Value (NPV) is a method used to determine the current net value of a future financial benefit, given an assumed inflation or interest rate. In other words, NPV is the total expected income or revenue from a project, minus the total expected cost of the project, taking into account the time-value of money.'
    ]
};

var bj_npvExample = {
    id: 'bj_13',
    title: 'Example',
    comment: [
                'Which of the following two projects is better to select if NPV is used as the selection criterion?',
                'Project A has a NPV of $1,500 and will be completed in 5 years.',
                'Project B has a NPV of $1,000 and will be completed in 1 year.',
                '<b>Solution</b>: ',
                'Project A, since its NPV is higher; the fact that Project B has a shorter duration than Project A is not considered here, because time is already accounted for in the NPV calculations (i.e., due to the fact that it is the current, not future value that is being considered in the calculation).'
    ]
};

var bj_irr = {
    id: 'bj_14',
    title: '3.	Internal Rate of Return (IRR)',
    comment: [
        'Internal Rate of Return (IRR) is a discount rate on an investment in which the present value of cash inflows is made equal to the present value of cash outflows for assessing a project’s rate of return. When comparing projects, one with a higher IRR is typically better.',
        'Though IRR is not used to justify projects as often as some other techniques, such as NPV, it is an important concept to know.'
    ]
};

var bj_irrExample = {
    id: 'bj_15',
    title: 'Example',
    comment: [
               'Based on IRR, which project is most desirable?',
               'Project A, which has an IRR of 15% and will be completed in 5 years.',
               'Project B, which has an IRR of 10% and will be completed in 1 year.',
               '<b>Solution</b>:',
               'Project A, since its IRR is higher; the fact that Project B has a shorter duration than Project A is not considered here because time is already taken into account in the IRR calculations (i.e., as with NPV, it is the current, not future value that is used to determine the IRR).'
    ]
};

var bj_VSM = {
    id: 'bj_16',
    title: '1.	Value Stream Mapping',
    comment: [
        'Value Stream Mapping uses flowcharts, to illustrate the flow of information needed to complete a process. This technique may be used to streamline a process by helping to determine non-value-added elements.'
    ]
};

var bj_customer = {
    id: 'bj_17',
    title: '2.	Customer Value-based Prioritization',
    comment: [
                'Customer Value-based Prioritization places primary importance on the customer and strives to implement User Stories with the highest value first. Such high value User Stories are identified and moved to the top of the Prioritized Product Backlog. A team can use a variety of prioritization schemes to determine high-value features.',
                '<b>a.	Simple Schemes</b>: Simple schemes involve labeling items as Priority “1”, “2”, “3” or “High”, “Medium” and “Low” and so on. Although this is a simple and straightforward approach, it can become problematic because there is often a tendency to label everything as Priority “1” or “High”. Even “High,” “Medium,” and “Low” prioritization schemes can encounter similar difficulties.',
                '<b>b.	MoSCoW Prioritization</b>: The MoSCoW prioritization scheme derives its name from the first letters of the phrases “Must have,” “Should have,” “Could have,” and “Won’t have”. This prioritization method is generally more effective than simple schemes. The labels are in decreasing order of priority with “Must have” features being those without which the product will have no value and “Won’t have” features being those that, although they would be nice to have, are not necessary to be included.',
                '<b>c.	Monopoly Money</b>: This technique involves giving the customer “monopoly money” or “false money” equal to the amount of the project budget and asking them to distribute it among the User Stories under consideration. In this way, the customer prioritizes based on what they are willing to pay for each User Story.',
                '<b>d.	100-Point Method</b>: The 100-Point Method was developed by Dean Leffingwell and Don Widrig (2003). It involves giving the customer 100 points they can use to vote for the features that they feel are most important.',
                '<b>e.	Kano Analysis</b>: The Kano analysis was developed by Noriaki Kano (1984) and involves classifying features or requirements into four categories based on customer preferences:',
                '<b>1.	Exciters/Delighters</b>: Features that are new, or of high value to the customer',
                '<b>2.	Satisfiers</b>: Features that offer value to the customer',
                '<b>3.	Dissatisfiers</b>: Features which, if not present, are likely to cause a customer to dislike the product, but do not affect the level of satisfaction if they are present',
                '<b>4.	Indifferent</b>: Features that will not affect the customer in any way and should be Eliminated',
                'Interestingly, features usually move down the classification list over time; customers will come to expect features (e.g., cameras on phones) and these features will move from being exciters/delighters to satisfiers and eventually to dissatisfiers.'
    ],
    image: '../images/kano.png'
};

var bj_ranking = {
    id: 'bj_18',
    title: 'Relative Prioritization Ranking',
    stitle: 'ranking',
    comment: [
            'A simple listing of User Stories in order of priority is an effective method for determining the desired User Stories for each iteration or release of the product or service. The purpose is to create a simple, single list with the goal of prioritizing features, rather than being distracted by multiple prioritization schemes.',
            'This simple list also provides a basis for incorporating changes and identified risks when necessary. Each change or identified risk can be inserted in the list based on its priority relative to the other User Stories in the list. Typically, new changes will be included at the expense of features that have been assigned a lower priority.',
            'Defining the Minimum Marketable Features (MMF) is extremely important during this process, so that the first release or iteration happens as early as possible, leading to increased ROI. Normally, these User Stories would rank highest in priority.'
    ]
};

var bj_story = {
    id: 'bj_19',
    stitle: 'story',
    title: 'Story Mapping',
    comment: [
        'This is a technique to provide a visual outline of the product and its key components. Story Mapping, first formulated by Jeff Patton (2005), is commonly used to illustrate product roadmaps Story maps depict the sequence of product development iterations and map out which features will be included in the first, second, third, and subsequent releases.'
    ]
};

var bj_32 = {
	id: 'bj_32',
	title: 'Overview',
    comment: [
        'The following sections deal with some of the tools used to assess and evaluate business justification, as well as some other aspects associated with project justification and project selection. It is not necessary, or even recommended to use every available technique for every project. Some techniques are not appropriate depending on the specific project, and techniques may be used to assess projects individually or to compare the expected value of multiple projects.',
        'The Scrum Guidance Body (SGB), which can be a panel of experts or a set of documents on organizational standards and procedures, defines the guidelines and metrics that will be used to assess business value. Each respective Product Owner, however, is responsible for performing the activities that verify and track business value for his or her respective projects, programs, or portfolios.'
    ]
};

var bj_33 = {
		id: 'bj_33',
        title: 'Estimation of Project Value',
        stitle: 'estimation',
        overview: {
            title: '',
            comment: [
                    'The value to be provided by business projects can be estimated using various methods such as Return on Investment (ROI), Net Present Value (NPV), and Internal Rate of Return (IRR).'
            ]
        },
        roi: {
            roi: bj_roi,
            example: bj_roiExample
        },
        npv: {
            npv: bj_npv,
            example: bj_npvExample
        },
        irr: {
            irr: bj_irr,
            example: bj_irrExample
        }
};

var bj_34 = {
		id: 'bj_34',
        title: 'Planning for Value',
        stitle: 'planning',
        overview: {
            title: 'Overview',
            comment: [
                'After justifying and confirming the value of a project, the Product Owner should consider the organizational policies, procedures, templates, and general standards dictated by the Scrum Guidance Body (or similar organizational project board or office) when planning a project; at the same time maximizing Value-driven Delivery. The onus for determining how the value is created falls on the stakeholders (sponsor, customers, and/or users), while the Scrum Team concentrates on what is to be developed. Some common tools recommended by a Scrum Guidance Body might include the following:'
            ]
        },
        value: bj_VSM,
        customer: bj_customer
};

var txtTechnique = {
    id: 'bj_20',
    title: 'Business Justification Techniques',
    overview: bj_32,
    estimation: bj_33,
    planning: bj_34,
    ranking: bj_ranking,
    story: bj_story
};

var bj_EVA = {
    id: 'bj_21',
	stitle: 'eva',
    title: 'Earned Value Analysis',
    comment: [
            'Although commonly used, tools such as bar charts and Gantt Charts have limitations in tracking and reporting progress when it comes to project performance. Earned Value Analysis (EVA) is used for this purpose. ',
            'EVA analyzes actual project performance against planned performance at a given point in time. For tracking techniques to be effective, the initial baseline project plan needs to be accurate. EVA often uses graphs and other visuals (e.g., S-curve), as a way to depict project status information.',
            'Earned Value Analysis measures current variances in the project’s schedule and cost performance and forecasts the final cost based on the determined current performance. EVA is typically done at the end of each Sprint after the User Stories in Sprint Backlog are completed.',
            'The table below, summarizes the formulas used in Earned Value Analysis.'
    ]
};

var bj_evaTable = {
    id: 'bj_22',
    title: 'table',
    nbcol: 3,
    head: ['Term Definition','Acronym', 'Formula'],
    body: [
        [['Planned Value'],['PV'],['']],
        [['Earned Value'],['EV'],['']],
        [['Actual Cost'],['AC'],['']],
        [['Budget at Completion'],['BAC'],['']],
        [['Schedule Variance'],['SV'],['EV - PV']],
        [['Cost Variance'],['CV'],['EV - AC']],
        [['Schedule Performance Index'],['SPI'],['EV / PV']],
        [['Cost Performance Index'],['CPI'],['EV / AC']],
        [['Percent Complete'],['% Complete'],['(EV / BAC) x 100']],
        [['Estimate at Completion'],['EAC'],['']],
        [['1. Estimating assumptions not valid'],[''],['AC + ETC']],
        [['2. Current Variances are atypical'],[''],['AC + BAC - EV']],
        [['3. Current Variances are typical'],[''],['BAC / CP']],
        [['Estimate to Complete'],['ETC'],['EAC - AC']],
        [['Variance at Completion'],['VAC'],['BAC - EAC']]
    ]
};

var bj_cfd = {
    id: 'bj_23',
    title: 'Cumulative Flow Diagram (CFD)',
    stitle: 'cfd',
    comment: [
            'A Cumulative Flow Diagram (CFD) is a useful tool for reporting and tracking project performance. It provides a simple, visual representation of project progress at a particular point in time. It is usually used to provide a higher level status of the overall project and not daily updates for individual Sprints.',
            'the figure below is an example of a CFD for a large project. It shows how many User Stories are yet to be created, in process of being created, and have been created. As customer requirements change, there is a change in the Cumulative User Stories which have to be delivered. Change points 1 and 2 are where the Product Owner removed existing user Stories in the Risk Adjusted Prioritized Product Backlog and Change points 3 and 4 are where the Product Owner added new User Stories in the Risk Adjusted Prioritized Product Backlog',
            'This type of diagram can be a great tool for identifying roadblocks and bottlenecks within processes. For example, if the diagram shows one band becoming narrower while the previous band is becoming wider over time, there may be a bottleneck and changes may be needed to increase efficiency and/or improve project performance.'
    ],
    image: '../images/cfd.png'
};

var bj_evaExample = {
    id: 'bj_24',
    title: 'Example',
    comment: [
            'A website with 4,000 web pages needs to be developed—we assume that every web page takes the same time to complete, and that each web page is a unique User Story of equal priority in the Prioritized Product Backlog. The estimated cost of completing the project is $400,000 and the time limit for the project is 12 months. After 6 months, $300,000 has been spent and the work completed is 1,000 web pages.',
            'What have we been provided with?',
            '•	Budget at Completion (BAC) = $400,000 (Cost Baseline for the project)',
            '•	Planned Value (PV) = $200,000 (since we planned to complete 2,000 web pages)',
            '•	Earned Value (EV) = $100,000 (value of 1,000 web pages that are complete)',
            '•	Actual Cost (AC) = $300,000 (what has been spent so far)',
            '<b>Formulas:</b>',
            '•	Schedule Variance (SV) = EV - PV = $100,000 - $200,000 = - $100,000',
            '•	Cost Variance (CV) = EV - AC = $100,000 - $300,000 = - $200,000',
            'o	The negative variances in our project indicate that we are behind schedule and over budget.',
            '•	Schedule Performance Index (SPI) = EV / PV = $100,000 / $200,000 = 0.5',
            'o	SPI < 1 indicates that the work completed so far is only 50% of what we planned to have completed at 6 months.',
            '•	Cost Performance Index (CPI) = EV / AC = $100,000 / $300,000 = 0.33',
            'o	CPI < 1 indicates that we are only getting 33% of work done for the amount of money being spent.',
            '•	Percent Complete = EV / BAC x 100 = $100,000 / $400,000 x 100 = 25%',
            'o	So, 25% of the work on the project is complete at this point in time.',
            '<b>S-curve</b> for the data:'
    ],
    image: '../images/s_curve.png'
};

var bj_35 = {
	id: 'bj_35',
    title: 'Continuous Value Justification',
    comment: [
        'Business value should be assessed regularly to determine whether the justification or viability of executing the project continues to exist. Frequent assessment of investment in the project relative to business value being created qualifies the continued viability of a project. The expected requirements from the project may change frequently, which can impact both project investment and value creation. A key aspect of Scrum is its ability to quickly adjust to chaos created by a rapidly changing business model. In projects with ambiguous user requirements and significant potential for frequent changes, Scrum provides considerable advantages over other development models.',
        'Monitoring the rate of delivering value is an important requirement for Scrum projects. Periodically tracking and reporting the creation of value assists in assessing project status and provides important information to the customer and other stakeholders.'
    ]
};

var bj_36 = {
	id: 'bj_36',
    title: 'Earned Value Analysis',
	stitle: 'eva',
	eva: bj_EVA,
	table: bj_evaTable,
	example: bj_evaExample
}

var txtContinuous = {
    id: 'bj_25',
    title: 'Continuous Value Justification',
    overview: bj_35,
    eva: bj_36,
    cfd: bj_cfd
};

var bj_prototype = {
    id: 'bj_26',
    title: 'Prototypes, Simulations, and Demonstrations',
    comment: [
        'Demonstrating prototypes to customers and simulating their functionalities are commonly used techniques for confirming value.',
        'Often, after using the features or having them demonstrated, customers can more clearly determine whether the features are adequate and suitable for their needs. They might realize a need for additional features, or may decide to modify previously defined feature requirements. In product development, this customer experience has come to be known as IKIWISI (I’ll Know It When I See It).',
        'Through demonstrations or access to early iterations, customers can also evaluate to what degree the team has successfully interpreted their requirements and met their expectations.'
    ]
};

var bj_37 = {
	id: 'bj_37',
        title: 'Confirm Benefits Realization',
        comment: [
            'Throughout a project, it is important to verify whether benefits are being realized. Whether the products of a Scrum project are tangible or intangible, appropriate verification techniques are required to confirm that the team is creating the deliverables that will achieve the benefits and value defined at the beginning of the project.'
        ]
    }

var txtBenefits = {
    id: 'bj_27',
    title: 'Confirm Benefits Realization',
    overview: bj_37,
    prototype: bj_prototype
};

var bj_summary = {
    id: 'bj_28',
	title: 'Responsibilities',
	nbcol: 2,
	head: ['Role','Responsibilities'],
	body: [
            [['Scrum Guidance Body'],['Establishes overall guidelines and metrics for evaluating value','Acts in a consulting capacity and provides guidance for projects, programs, and portfolios as required']],
            [['Portfolio Product Owner'],['Ensures value delivery for portfolios','Creates the business justification for portfolios','Provides value guidance for programs within portfolios','Approves the business justification of programs within a portfolio']],
            [['Portfolio Scrum Master'],['Ensures the desired outcomes of the portfolio are achieved','Performs Continuous Value Justification for portfolios']],
            [['Program Product Owner'],['Ensures value delivery for programs','Creates the business justification for programs','Provides value guidance for projects within a program','Approves the business justification of projects within a program']],
            [['Program Scrum Master'],[ 'Ensures the desired outcomes of the program are communicated and understood','Performs Continuous Value Justification for programs']],
            [['Stakeholder(s)'],['Helps prioritize User Stories and requirements in the Prioritized Product Backlog','Communicates with Scrum Team and confirms realization of value at the end of every Sprint, Release, and the project']],
            [['Product Owner'],['Ensures value delivery for projects','Maintains the business justification for projects','Confirms and communicates project benefits to stakeholders']],
            [['Scrum Master'],['Ensures the desired outcomes of the project are communicated to and understood by the Scrum Team','Performs Continuous Value Justification for projects']],
            [['Scrum Team'],['Ensures that project deliverables are completed in accordance with agreed Acceptance Criteria','Performs Continuous Value Justification for projects']]
        ]
}

var txtSummary = {
    id: 'bj_29',
    title: 'Business Justification: Summary of Responsibilities',
    table: bj_summary
};

var txtVersus = {
    id: 'bj_30',
    title: 'Business justification: Scrum vs. Traditional Project Management',
    comment: [
        'Traditional projects emphasize on extensive upfront planning and adherence to the project plan created by the project manager. Usually, changes are managed through a formal change management system and value is created at the end of the project when the final product is delivered.',
        'In Scrum projects, extensive long-term planning is not done prior to project execution. Planning is done in an iterative manner before each Sprint. This allows quick and effective response to change, which results in lower costs and ultimately increased profitability and Return on Investment (ROI). Moreover, Value-Driven Delivery (section 4.3) is a key benefit of the Scrum framework and provides significantly better prioritization and quicker realization of business value. Because of the iterative nature of Scrum development, there is always at least one release of the product with Minimum Marketable Features (MMF) available. Even if a project is terminated, there are usually some benefits or value created prior to termination.'
    ]
};

exports.txtIntro = txtIntro; // bj_01
exports.txtRole = txtRole; // bj_02
exports.txtVdd = txtVdd; // bj_06
exports.txtImportance = txtImportance; // bj_09
exports.txtTechnique = txtTechnique; // bj_20
exports.txtContinuous = txtContinuous; // bj_25
exports.txtBenefits = txtBenefits; // bj_27
exports.txtVersus = txtVersus; // bj_29
exports.txtSummary = txtSummary; // bj_30

exports.bj_VDD = bj_VDD // bj_03
exports.bj_responwer = bj_responwer // bj_04
exports.bj_respother = bj_respother // bj_05
exports.bj_factors = bj_factors // bj_07
exports.bj_lifecycle = bj_lifecycle // bj_08
exports.bj_roi = bj_roi // bj_10
exports.bj_roiExample = bj_roiExample // bj_11
exports.bj_npv = bj_npv // bj_12
exports.bj_npvExample = bj_npvExample // bj_13
exports.bj_irr = bj_irr // bj_14
exports.bj_irrExample = bj_irrExample // bj_15
exports.bj_VSM = bj_VSM // bj_16
exports.bj_customer = bj_customer // bj_17
exports.bj_ranking = bj_ranking // bj_18
exports.bj_story = bj_story // bj_19
exports.bj_EVA = bj_EVA // bj_21
exports.bj_evaTable = bj_evaTable // bj_22
exports.bj_cfd = bj_cfd // bj_23
exports.bj_evaExample = bj_evaExample // bj_24
exports.bj_prototype = bj_prototype // bj_26
exports.bj_summary = bj_summary // bj_28
// 37